# Generated by Django 5.1.2 on 2025-01-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomrole',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientcustomrole', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='organizations.organization'),
        ),
    ]
