# Generated by Django 5.1.2 on 2025-01-14 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_verified_alter_user_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('token_type', models.CharField(blank=True, choices=[('CLIENT', 'Client'), ('INTERVIEWER', 'Interviewer'), ('INTERNAL', 'Internal'), ('AGENCY', 'Agency')], max_length=50, null=True)),
                ('access_token', models.TextField(help_text='Access token for API authentication.')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token to renew the access token.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp.')),
                ('scope', models.TextField(blank=True, help_text='Granted scopes for the token.', null=True)),
                ('user', models.OneToOneField(help_text='The user associated with these tokens.', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
