# Generated by Django 5.1.2 on 2025-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='expires_at',
            field=models.DateTimeField(help_text='Access Token expiration timestamp.'),
        ),
    ]
