# Generated by Django 5.1.2 on 2025-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_email_verified_alter_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('client_admin', 'Client Admin'), ('client_owner', 'Client Owner'), ('client_user', 'Client User'), ('user', 'User'), ('interviewer', 'Interviewer'), ('agency', 'Agency')], default='user', max_length=15),
        ),
    ]
