# Generated by Django 5.1.2 on 2025-03-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_email_verified_alter_user_phone_verified'),
        ('core', '0008_alter_user_role'),
    ]

    operations = [
    ]
