# Generated by Django 5.1.2 on 2025-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_time',
            field=models.TimeField(help_text='duration', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
