# Generated by Django 5.1.2 on 2025-01-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_job_interview_time_alter_job_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description_file',
            field=models.FileField(blank=True, upload_to='job_descriptions'),
        ),
        migrations.AlterField(
            model_name='job',
            name='other_details',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='reason_for_archived',
            field=models.CharField(blank=True, choices=[('PF', 'Position Filled'), ('POH', 'Position On Hold'), ('OTH', 'Other')], max_length=15, null=True),
        ),
    ]
