# Generated by Django 5.1.2 on 2025-01-14 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_job_job_description_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerSlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('slot_time', models.DateTimeField(help_text='The date and time of the slot booking.')),
                ('is_booked', models.BooleanField(default=False, help_text='Indicates whether the slot has been booked or not.')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the slot booking.', null=True)),
                ('booked_by', models.ForeignKey(blank=True, help_text='The user who booked the slot, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(help_text='The interviewer associated with this slot booking.', on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_slots', to='dashboard.internalinterviewer')),
            ],
            options={
                'verbose_name': 'Interviewer Slot Booking',
                'verbose_name_plural': 'Interviewer Slot Bookings',
                'ordering': ['slot_time'],
                'unique_together': {('interviewer', 'slot_time')},
            },
        ),
    ]
