# Generated by Django 5.1.2 on 2025-01-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_internalinterviewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweravailability',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
