# Generated by Django 5.1.2 on 2025-02-01 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_intervieweravailability_google_calendar_id'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('years_of_experience', models.CharField(choices=[('0 - 4 years', '0 - 4 Years'), ('4 - 6 years', '4 - 6 Years'), ('6 - 8 years', '6 - 8 Years'), ('8 - 10 years', '8 - 10 Years'), ('10+ years', '10+ Years')], max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('organization', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
