# Generated by Django 5.1.2 on 2025-02-05 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_intervieweravailability_google_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_dropping',
            field=models.CharField(blank=True, choices=[('CNI', 'Candidate Not Interested'), ('CNA', 'Candidate Not Available'), ('CNR', 'Candidate Not Responded'), ('OTH', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended'), ('SCH', 'Schedule'), ('NSCH', 'Not Schedule'), ('NJ', 'Not Joined')], default='NSCH', help_text='candidate interview status', max_length=15),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interviews', to='dashboard.candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended'), ('SCH', 'Schedule'), ('NSCH', 'Not Schedule'), ('NJ', 'Not Joined')], help_text='Interview status', max_length=15),
        ),
    ]
