# Generated by Django 5.1.2 on 2025-02-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_agreement'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-4', '0 - 4 Years'), ('4-6', '4 - 6 Years'), ('6-8', '6 - 8 Years'), ('8-10 years', '8 - 10 Years'), ('10+', '10+ Years')], max_length=50),
        ),
    ]
