# Generated by Django 5.1.2 on 2025-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_candidate_reason_for_dropping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='final_selection_status',
            field=models.CharField(blank=True, choices=[('RJD', 'Rejected'), ('SLD', 'Selected'), ('HD', 'Hold')], max_length=20, null=True),
        ),
    ]
