# Generated by Django 5.1.2 on 2025-02-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_candidate_final_selection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('TG', 'Transgender')], max_length=2),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('INT', 'Internal'), ('AGN', 'Agency'), ('CLT', 'Client')], help_text='From Which side this candidate is ?', max_length=3),
        ),
    ]
