# Generated by Django 5.1.2 on 2025-02-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_candidate_gender_alter_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_dropping',
            field=models.CharField(blank=True, choices=[('CNI', 'Candidate Not Interested'), ('CNA', 'Candidate Not Available'), ('CNR', 'Candidate Not Responded'), ('OTH', 'Others')], max_length=100, null=True),
        ),
    ]
