# Generated by Django 5.1.2 on 2025-02-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_candidate_reason_for_dropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate', to='dashboard.job'),
        ),
    ]
