# Generated by Django 5.1.2 on 2025-02-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_candidate_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='recruiters', to='dashboard.clientuser'),
        ),
    ]
