# Generated by Django 5.1.2 on 2025-02-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_job_client_job_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='clients',
        ),
    ]
