# Generated by Django 5.1.2 on 2025-02-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_rename_client_job_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='dashboard.clientuser'),
        ),
    ]
