# Generated by Django 5.1.2 on 2025-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_job_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='accessibility',
            field=models.CharField(blank=True, choices=[('AJ', 'All jobs'), ('AGJ', 'Assigned jobs')], max_length=5),
        ),
    ]
