# Generated by Django 5.1.2 on 2025-02-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_clientuser_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, upload_to='candidate_cvs'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='specialization',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('fullstack', 'Fullstack'), ('aiml', 'AI/ML'), ('devops', 'DevOps'), ('data_engineer', 'Data Engineering'), ('testing', 'Testing/QA'), ('android', 'Android'), ('ios', 'iOS'), ('mobile', 'Mobile (Android + iOS)')], max_length=100),
        ),
    ]
