# Generated by Django 5.1.2 on 2025-02-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_candidate_cv_alter_candidate_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='interivewer',
            new_name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='reschedule',
        ),
        migrations.RemoveField(
            model_name='intervieweravailability',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='interview',
            name='previous_interview',
            field=models.ForeignKey(blank=True, help_text='Reference to the previous interview instance if rescheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_interviews', to='dashboard.interview'),
        ),
    ]
