# Generated by Django 5.1.2 on 2025-02-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0019_rename_interivewer_interview_interviewer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervieweravailability",
            name="recurrence_rule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="internalinterviewer",
            name="strength",
            field=models.CharField(
                blank=True,
                choices=[
                    ("frontend", "Frontend"),
                    ("backend", "Backend"),
                    ("fullstack", "Fullstack"),
                    ("aiml", "AI/ML"),
                    ("devops", "DevOps"),
                    ("data_engineer", "Data Engineering"),
                    ("testing", "Testing/QA"),
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("mobile", "Mobile (Android + iOS)"),
                ],
                max_length=50,
            ),
        ),
    ]
