# Generated by Django 5.1.2 on 2025-02-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_intervieweravailability_recurrence_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='mandatory_skills',
        ),
    ]
