# Generated by Django 5.1.2 on 2025-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_job_mandatory_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mandatory_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
