# Generated by Django 5.1.2 on 2025-02-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalinterviewer',
            name='assigned_roles',
            field=models.CharField(blank=True, choices=[('SDE_I', 'SDE-I'), ('SDE_II', 'SDE-II'), ('SDE_III', 'SDE-III'), ('PE', 'Principal Engineer'), ('EM', 'Engineering Manager'), ('TL', 'Technical Lead'), ('VPE', 'VP Engineering'), ('DOE', 'Director of Engineering'), ('DE', 'DevOps Engineer'), ('SR_DE', 'Senior DevOps Engineer'), ('LD_DE', 'Lead DevOps Engineer'), ('SDET', 'SDET'), ('SR_SDET', 'Sr. SDET'), ('MGR_SDET', 'Manager-SDET'), ('DIR_SDET', 'Director-SDET'), ('MLS', 'ML Scientist'), ('SR_MLS', 'Sr. ML Scientist'), ('LD_MLS', 'Lead ML Scientist'), ('P_MLS', 'Principal ML Scientist'), ('DEE', 'Data Engineer'), ('SR_DEE', 'Sr. Data Engineer'), ('LD_DEE', 'Lead Data Engineer'), ('P_DEE', 'Principal Data Engineer')], max_length=15),
        ),
    ]
