# Generated by Django 5.1.2 on 2025-02-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_internalinterviewer_assigned_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervieweravailability',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
