# Generated by Django 5.1.2 on 2025-02-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_intervieweravailability_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('SCH', 'Scheduled'), ('NSCH', 'Not Scheduled'), ('RESCH', 'Rescheduled'), ('NJ', 'Not Joined'), ('PENDING_EVAL', 'Pending Evaluation'), ('COMPLETED', 'Completed'), ('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended')], default='NSCH', help_text='candidate interview status', max_length=15),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('SCH', 'Scheduled'), ('NSCH', 'Not Scheduled'), ('RESCH', 'Rescheduled'), ('NJ', 'Not Joined'), ('PENDING_EVAL', 'Pending Evaluation'), ('COMPLETED', 'Completed'), ('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended')], help_text='Interview status', max_length=15)),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled interview date and time')),
                ('recording', models.FileField(blank=True, help_text='Interview recording file', null=True, upload_to='interview_recordings')),
                ('feedback', models.TextField(blank=True, help_text='Feedback for the candidate', null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('candidate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interviews', to='dashboard.candidate')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interviews', to='dashboard.internalinterviewer')),
                ('previous_interview', models.ForeignKey(blank=True, help_text='Reference to the previous interview instance if rescheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_interviews', to='dashboard.interview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_requests', to='dashboard.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='dashboard.internalinterviewer')),
            ],
            options={
                'unique_together': {('interviewer', 'interview')},
            },
        ),
    ]
