# Generated by Django 5.1.2 on 2025-02-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_candidate_status_interview_interviewerrequest'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('YET_TO_JOIN', 'Yet To Join'), ('DOUBTFUL', 'Doubtful')], default='YET_TO_JOIN', max_length=11)),
                ('notice_period', models.CharField(choices=[('0-7', '0-7 days'), ('8-15', '8-15 days'), ('16-30', '16-30 days'), ('31-45', '31-45 days'), ('46-60', '46-60 days'), ('61-75', '61-75 days'), ('76-90', '76-90 days')], default='16-30', max_length=10)),
                ('offered', models.BooleanField(default=False)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('offer_accepted', models.BooleanField(default=False)),
                ('other_offer', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='dashboard.candidate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='dashboard.clientuser')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='dashboard.job')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('template_html_content', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagementtemplates', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('PED', 'Pending'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PED', max_length=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='engagement_attachments/')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagementoperations', to='dashboard.engagement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagementoperations', to='dashboard.engagementtemplates')),
            ],
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('candidate', 'jobs'), name='unique_engagement'),
        ),
    ]
