# Generated by Django 5.1.2 on 2025-02-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_engagement_engagementtemplates_engagementoperation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagementoperation',
            old_name='operation_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='engagementoperation',
            name='attachment',
        ),
        migrations.AddField(
            model_name='engagementtemplates',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='engagement_attachments/'),
        ),
    ]
