# Generated by Django 5.1.2 on 2025-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_rename_operation_date_engagementoperation_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagement',
            name='unique_engagement',
        ),
        migrations.RenameField(
            model_name='engagement',
            old_name='jobs',
            new_name='job',
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='unique_engagement'),
        ),
    ]
