# Generated by Django 5.1.2 on 2025-02-19 13:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_engagement_candidate_cv_engagement_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='candidate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True),
        ),
    ]
