# Generated by Django 5.1.2 on 2025-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_engagement_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('YTJ', 'Yet to Join'), ('DBT', 'Doubtful'), ('JND', 'Joined'), ('DCL', 'Declined'), ('OHD', 'On Hold')], default='YET_TO_JOIN', max_length=11),
        ),
    ]
