# Generated by Django 5.1.2 on 2025-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_alter_engagement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementtemplates',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
