# Generated by Django 5.1.2 on 2025-02-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_engagementtemplates_subject'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='engagementoperation',
            constraint=models.UniqueConstraint(fields=('engagement', 'template'), name='unique_engagement_operation'),
        ),
    ]
