# Generated by Django 5.1.2 on 2025-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_engagementoperation_unique_engagement_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementoperation',
            name='task_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
