# Generated by Django 5.1.2 on 2025-02-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_engagementoperation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementoperation',
            name='week',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('YTJ', 'Yet to Join'), ('DBT', 'Doubtful'), ('JND', 'Joined'), ('DCL', 'Declined'), ('OHD', 'On Hold')], default='YTJ', max_length=11),
        ),
    ]
