# Generated by Django 5.1.2 on 2025-02-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_agreement_organization_and_more'),
        ('dashboard', '0036_engagementoperation_week_alter_engagement_status'),
    ]

    operations = [
    ]
