# Generated by Django 5.1.2 on 2025-02-22 13:41

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_engagementoperation_week_alter_engagement_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDIPUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('USER', 'user'), ('AGENCY', 'agency')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN', unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='dashboard.internalclient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
