# Generated by Django 5.1.2 on 2025-02-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_merge_20250223_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementoperation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engagementoperation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
