# Generated by Django 5.1.2 on 2025-03-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0038_hdipusers_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hdipusers",
            name="client",
        ),
        migrations.RemoveField(
            model_name="hdipusers",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hdipusers",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="hdipusers",
            name="role",
        ),
        migrations.RemoveField(
            model_name="internalclient",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="internalclient",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internalclients",
                to="dashboard.hdipusers",
            ),
        ),
    ]
