# Generated by Django 5.1.2 on 2025-02-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_engagementoperation_archived_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagementoperation',
            name='unique_engagement_operation',
        ),
    ]
