# Generated by Django 5.1.2 on 2025-03-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_remove_hdipusers_client_remove_hdipusers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='accessibility',
            field=models.CharField(blank=True, choices=[('AJ', 'All jobs'), ('AGJ', 'Assigned jobs')], default='AJ', max_length=5),
        ),
    ]
