# Generated by Django 5.1.2 on 2025-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_remove_engagementoperation_unique_engagement_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementoperation',
            name='operation_complete_status',
            field=models.CharField(choices=[('PED', 'Pending'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PED', help_text='Operation Completation Status', max_length=15),
        ),
        migrations.AlterField(
            model_name='engagementoperation',
            name='delivery_status',
            field=models.CharField(choices=[('PED', 'Pending'), ('SUC', 'Success'), ('FLD', 'Failed')], default='PED', help_text='Email Delivery Status', max_length=15),
        ),
    ]
