# Generated by Django 5.1.2 on 2025-03-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_clientuser_accessibility'),
        ('dashboard', '0040_engagementoperation_operation_complete_status_and_more'),
    ]

    operations = [
    ]
