# Generated by Django 5.1.2 on 2025-03-03 16:41

from django.db import migrations, models


def add_designation_domains(app, schema_editor):
    designation_domain = app.get_model("dashboard", "DesignationDomain")
    predefined_domains = [
        "SDE_I",
        "SDE_II",
        "SDE_III",
        "PE",
        "EM",
        "TL",
        "VPE",
        "DOE",
        "DE",
        "SR_DE",
        "LD_DE",
        "SDET",
        "SR_SDET",
        "MGR_SDET",
        "DIR_SDET",
        "MLS",
        "SR_MLS",
        "LD_MLS",
        "P_MLS",
        "DEE",
        "SR_DEE",
        "LD_DEE",
        "P_DEE",
    ]
    for domain in predefined_domains:
        designation_domain.objects.get_or_create(name=domain)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0041_merge_20250303_1122"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignationDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=15, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="internalinterviewer",
            name="assigned_roles",
        ),
        migrations.AddField(
            model_name="internalinterviewer",
            name="assigned_domains",
            field=models.ManyToManyField(
                blank=True,
                related_name="interviewers",
                to="dashboard.designationdomain",
            ),
        ),
        migrations.RunPython(add_designation_domains),
    ]
