# Generated by Django 5.1.2 on 2025-03-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_designationdomain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
