# Generated by Django 5.1.2 on 2025-03-09 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_job_specialization"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engagement",
            name="client",
        ),
        migrations.AddField(
            model_name="engagement",
            name="gtp_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="engagement",
            name="gtp_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="engagement",
            name="organization",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagements",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
    ]
