# Generated by Django 5.1.2 on 2025-03-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_engagement_client_engagement_gtp_email_and_more'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='organizations.organization'),
        ),
    ]
