# Generated by Django 5.1.2 on 2025-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_agreement_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='years_of_experience',
            field=models.CharField(blank=True, choices=[('0-4', '0 - 4 Years'), ('4-6', '4 - 6 Years'), ('6-8', '6 - 8 Years'), ('8-10', '8 - 10 Years'), ('10+', '10+ Years')], max_length=50),
        ),
    ]
