# Generated by Django 5.1.2 on 2025-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_alter_agreement_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_scheduled_initiate_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Gives the clarity the weather reinitiate the schedule again or not.', null=True),
        ),
    ]
