# Generated by Django 5.1.2 on 2025-03-19 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_candidate_last_scheduled_initiate_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('skill_based_performance', models.JSONField(default=dict)),
                ('skill_evaluation', models.JSONField(default=dict)),
                ('strength', models.CharField(max_length=500)),
                ('improvement_points', models.CharField(max_length=500)),
                ('overall_remark', models.CharField(choices=[('HREC', 'Strongly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended')], max_length=10)),
                ('overall_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Score should be greater than or equal to 0'), django.core.validators.MaxValueValidator(100, message='Scroe must not exceed 100')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(help_text="The interviewer's feedback on interview.", on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to='dashboard.interview')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
