# Generated by Django 5.1.2 on 2025-03-19 15:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_interviewfeedback_overall_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='improvement_points',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview',
            field=models.ForeignKey(blank=True, help_text="The interviewer's feedback on interview.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to='dashboard.interview'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='overall_remark',
            field=models.CharField(blank=True, choices=[('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended'), ('NJ', 'Not Joined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='overall_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Score should be greater than or equal to 0'), django.core.validators.MaxValueValidator(100, message='Scroe must not exceed 100')]),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='skill_based_performance',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='skill_evaluation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='strength',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
