# Generated by Django 5.1.2 on 2025-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_interviewfeedback_improvement_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='improvement_points',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='overall_remark',
            field=models.CharField(choices=[('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended'), ('NJ', 'Not Joined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='skill_based_performance',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='skill_evaluation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='strength',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
