# Generated by Django 5.1.2 on 2025-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_interviewfeedback_improvement_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_service_account_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
