# Generated by Django 5.1.2 on 2025-03-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_interview_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='interview',
            field=models.OneToOneField(blank=True, help_text="The interviewer's feedback on interview.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to='dashboard.interview'),
        ),
    ]
