# Generated by Django 5.1.2 on 2025-03-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_interviewfeedback_interview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('interviewer', 'scheduled_time')},
        ),
    ]
