# Generated by Django 5.1.2 on 2025-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_interview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='downloaded',
            field=models.BooleanField(default=False, help_text='signifies that video is downloaded and stored'),
        ),
        migrations.AddField(
            model_name='interview',
            name='transcription',
            field=models.FileField(blank=True, help_text='recordings transcribe files', null=True, upload_to='interview_recordings_transcription'),
        ),
    ]
