# Generated by Django 5.1.2 on 2025-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_interview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
