# Generated by Django 5.1.2 on 2025-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_candidate_current_designation'),
        ('dashboard', '0055_interview_downloaded_interview_transcription'),
    ]

    operations = [
    ]
