# Generated by Django 5.1.2 on 2025-03-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_merge_20250325_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='Signify whether the interviewer has submitted their feedback for this interview or not.'),
        ),
    ]
