# Generated by Django 5.1.2 on 2025-03-29 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_interviewfeedback_is_submitted'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('record_type', models.CharField(blank=True, choices=[('CLB', 'Client Billing'), ('INP', 'Interviewer Payment')], max_length=15, null=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('PAI', 'Paid'), ('OVER', 'Overdue'), ('CAN', 'Cancelled'), ('FLD', 'Failed'), ('INP', 'Inprogress')], default='PEN', max_length=15)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('experience_level', models.CharField(choices=[('0-4', '0 - 4 Years'), ('4-6', '4 - 6 Years'), ('6-8', '6 - 8 Years'), ('8-10', '8 - 10 Years'), ('10+', '10+ Years')], max_length=10, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='client_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['organization', 'years_of_experience'], name='dashboard_a_organiz_46bdd1_idx'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='dashboard.internalclient'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='dashboard.internalinterviewer'),
        ),
        migrations.AddIndex(
            model_name='billingrecord',
            index=models.Index(fields=['record_type', 'status'], name='dashboard_b_record__9f48e6_idx'),
        ),
    ]
