# Generated by Django 5.1.2 on 2025-03-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_billingrecord_interviewerpricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('PED', 'Pending'), ('PAI', 'Paid'), ('OVER', 'Overdue'), ('CAN', 'Cancelled'), ('FLD', 'Failed'), ('INP', 'Inprogress')], default='PED', max_length=15),
        ),
    ]
