# Generated by Django 5.1.2 on 2025-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_billingrecord_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='no_of_time_processed',
            field=models.IntegerField(default=0, help_text="Signifying the number of times that task is processed. if the task process more that 3 times then the interview doesn't happen."),
        ),
    ]
