# Generated by Django 5.1.2 on 2025-04-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_interview_no_of_time_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='dashboard.clientuser'),
        ),
    ]
