# Generated by Django 5.1.2 on 2025-04-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_candidate_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalclient',
            name='client_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internalinterviewer',
            name='interviewer_level',
            field=models.IntegerField(default=0),
        ),
    ]
