# Generated by Django 5.1.2 on 2025-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_job_is_diversity_hiring_alter_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_report'),
        ),
    ]
