# Generated by Django 5.1.2 on 2025-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_interviewfeedback_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[('SCH', 'Scheduled'), ('CSCH', 'Compete Scheduled'), ('NSCH', 'Not Scheduled'), ('RESCH', 'Rescheduled'), ('NJ', 'Not Joined'), ('PENDING_EVAL', 'Pending Evaluation'), ('COMPLETED', 'Completed'), ('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended')], default='NSCH', help_text='candidate interview status', max_length=15),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(blank=True, choices=[('SCH', 'Scheduled'), ('CSCH', 'Compete Scheduled'), ('NSCH', 'Not Scheduled'), ('RESCH', 'Rescheduled'), ('NJ', 'Not Joined'), ('PENDING_EVAL', 'Pending Evaluation'), ('COMPLETED', 'Completed'), ('HREC', 'Highly Recommended'), ('REC', 'Recommended'), ('NREC', 'Not Recommended'), ('SNREC', 'Strongly Not Recommended')], help_text='Interview status', max_length=15),
        ),
    ]
