# Generated by Django 5.1.2 on 2025-04-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_alter_candidate_status_alter_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='source',
            field=models.CharField(blank=True, choices=[('INT', 'Internal'), ('AGN', 'Agency')], help_text='From Which side this candidate is ?', max_length=3),
        ),
    ]
