# Generated by Django 5.1.2 on 2025-04-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_candidate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
