# Generated by Django 5.1.2 on 2025-04-14 15:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_engagement_job'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagement',
            name='unique_engagement',
        ),
        migrations.AlterField(
            model_name='engagement',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='candidate_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN'),
        ),
    ]
