# Generated by Django 5.1.2 on 2025-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_remove_engagement_unique_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments'),
        ),
    ]
