# Generated by Django 5.1.2 on 2025-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_interviewfeedback_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedback',
            name='link',
            field=models.URLField(blank=True, help_text='interview_answer_link_if_any', null=True),
        ),
    ]
