# Generated by Django 5.1.2 on 2025-04-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_interviewscheduleattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_availablity', to='dashboard.intervieweravailability'),
        ),
    ]
