# Generated by Django 5.1.2 on 2025-04-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_interview_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.DateTimeField(help_text='Scheduled interview date and time', null=True),
        ),
    ]
