# Generated by Django 5.1.2 on 2025-04-24 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_alter_interview_scheduled_time'),
        ('organizations', '0006_alter_organization_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientuser',
            index=models.Index(fields=['name', 'status'], name='dashboard_c_name_683c1b_idx'),
        ),
    ]
