# Generated by Django 5.1.2 on 2025-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_clientuser_dashboard_c_name_683c1b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewfeedback',
            name='improvement_points',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='strength',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
