# Generated by Django 5.1.2 on 2025-05-02 14:59

from django.db import migrations, models


def set_billing_month(apps, schema_editor):
    BillingRecord = apps.get_model("dashboard", "BillingRecord")
    for record in BillingRecord.objects.all():
        billing_month = record.created_at.replace(day=1).date()
        record.billing_month = billing_month
        record.save(update_fields=["billing_month"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_alter_interviewfeedback_improvement_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="billing_month",
            field=models.DateField(
                null=True, blank=True, db_index=True, editable=False
            ),
        ),
        migrations.RunPython(set_billing_month),
    ]
