# Generated by Django 5.1.2 on 2025-05-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_auto_20250502_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewerpricing',
            name='experience_level',
            field=models.CharField(choices=[('0-4', '0 - 4 Years'), ('4-7', '4 - 7 Years'), ('7-10', '7 - 10 Years'), ('10+', '10+ Years')], max_length=10, unique=True),
        ),
    ]
