# Generated by Django 5.1.2 on 2025-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_interview_is_billing_completed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(fields=('client', 'billing_month'), name='unique_client_billing_per_month'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(fields=('interviewer', 'billing_month'), name='unique_interviewer_billing_per_month'),
        ),
    ]
