# Generated by Django 5.1.2 on 2025-05-03 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_billingrecord_unique_client_billing_per_month_and_more'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='client_amount',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='interviewer_amount',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='is_billing_completed',
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='billing_month',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BillingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('amount_for_client', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_for_interviewer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.CharField(choices=[('feedback_submitted', 'Feedback Submitted'), ('late_rescheduled', 'Late Rescheduled')], max_length=50)),
                ('billing_month', models.DateField()),
                ('is_billing_calculated', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.internalinterviewer')),
            ],
            options={
                'unique_together': {('interview', 'reason')},
            },
        ),
    ]
