# Generated by Django 5.1.2 on 2025-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_remove_interview_client_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='final_selection_status',
            field=models.CharField(blank=True, choices=[('R1R', 'Round 1 Reject'), ('R2R', 'Round 2 Reject'), ('R3R', 'Round 3 Reject'), ('R4R', 'Round 4 Reject'), ('OFD', 'Offer Decline'), ('HMR', 'HM Reject'), ('SLD', 'Selected'), ('HD', 'Hold')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='reason_for_dropping',
            field=models.CharField(blank=True, choices=[('CNI', 'Candidate Not Interested'), ('CNA', 'Candidate Not Available'), ('CNR', 'Candidate Not Responded'), ('OTH', 'Others'), ('RJD', 'Rejected By HDIP')], max_length=100, null=True),
        ),
    ]
