# Generated by Django 5.1.2 on 2025-05-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_alter_candidate_final_selection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalinterviewer',
            name='account_number',
            field=models.CharField(blank=True, help_text='bank a/c number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internalinterviewer',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='bank ifsc code', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='internalinterviewer',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='A dictionary of social media links related to the interviewer.'),
        ),
    ]
