# Generated by Django 5.1.2 on 2025-05-09 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_internalinterviewer_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='billingrecord',
            name='razorpay_signature',
        ),
        migrations.CreateModel(
            name='BillPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_link_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('SUC', 'Success'), ('FLD', 'Failed'), ('UDP', 'User Dropped'), ('CNL', 'Cancelled'), ('VOD', 'Void')], max_length=15)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('link_expired_time', models.DateTimeField()),
                ('cf_link_id', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('meta_data', models.JSONField(default=dict)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_payments', to='dashboard.billingrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
