# Generated by Django 5.1.2 on 2025-05-10 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_billingrecord_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
