# Generated by Django 5.1.2 on 2025-05-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_alter_billingrecord_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayments',
            name='payment_link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billpayments',
            name='payment_status',
            field=models.CharField(choices=[('SUC', 'Success'), ('FLD', 'Failed'), ('UDP', 'User Dropped'), ('CNL', 'Cancelled'), ('VOD', 'Void'), ('PED', 'Pending'), ('INA', 'Inactive')], default='PED', max_length=15),
        ),
    ]
