# Generated by Django 5.1.2 on 2025-05-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_billpayments_payment_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayments',
            name='link_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('PRT', 'Partially Paid'), ('EXP', 'Expired'), ('CNL', 'Cancelled')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billpayments',
            name='payment_link_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
