# Generated by Django 5.1.2 on 2025-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0087_billpayments_link_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='status',
            field=models.CharField(choices=[('PED', 'Pending'), ('PAI', 'Paid'), ('OVD', 'Overdue'), ('CAN', 'Cancelled'), ('FLD', 'Failed'), ('INP', 'Inprogress'), ('MMP', 'Mid-Month Payment'), ('PIP', 'Post Invoice, Pre Due'), ('LTD', 'Late Payment')], default='PED', max_length=15),
        ),
    ]
