# Generated by Django 5.1.2 on 2025-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_alter_candidate_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_engagement_pushed',
            field=models.BooleanField(default=False),
        ),
    ]
